# Generated by Django 4.0.6 on 2022-08-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('favicon', models.ImageField(blank=True, default='/favicon-96x96.png', null=True, upload_to='logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('mobile', models.CharField(max_length=20)),
                ('mobile2', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('copyright_year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'CompanyProfile',
                'verbose_name_plural': 'CompanyProfile',
                'db_table': 'companyprofile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateField(auto_now_add=True)),
                ('cleared', models.DateField(auto_now=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Cleared', 'Cleared')], default='New', max_length=50)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
                'db_table': 'contact',
                'managed': True,
            },
        ),
    ]
