# Generated by Django 4.0.6 on 2022-08-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='title',
            field=models.CharField(default='a', max_length=250),
        ),
    ]
