# Generated by Django 4.0.6 on 2022-08-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0003_alter_companyprofile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, null=True, upload_to='services')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
                'db_table': 'service',
                'managed': True,
            },
        ),
    ]
