# Generated by Django 4.0.6 on 2022-08-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0004_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
