# Generated by Django 4.0.6 on 2022-08-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0005_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateField(auto_now_add=True)),
                ('cleared', models.DateField(auto_now=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Cleared', 'Cleared')], default='New', max_length=50)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
                'db_table': 'contact',
                'managed': True,
            },
        ),
    ]
